### User login
# @name login
POST http://mojakgp-api.devm/api/login
Content-Type: application/json
Cookie: XDEBUG_SESSION=start

{
    "email": "laqutel@mailinator.com",
    "password": "adminadmin1"
}

### User logout
@usertoken = {{login.response.body.token}}

POST http://mojakgp-api.devm/api/logout
Content-Type: application/json
Cookie: XDEBUG_SESSION=start

{
    "api_token": "{{usertoken}}"
}