### User login
POST http://mojakgp-api.devm/api/login
Content-Type: application/json
Cookie: XDEBUG_SESSION=start

{
    "email": "mateusz.rycombel84@gmail.com",
    "password": "adminadmin1"
}

### User logout
POST http://mojakgp-api.devm/api/logout
Content-Type: application/json
Cookie: XDEBUG_SESSION=start

{
    "api_token": "lHLzviATdlsFedXcySUWqFOYGEyo4gaCUsHwtmgfFE4PkbQQUbMDzbda4t6l"
}